meta_product_name: "HIRED!"
meta_title: "Hired! Manage your job"
meta_description: "Take the stress out. Save time
Manage your job search journey with Hired!"
meta_image: "icon.png" # should exist in `app/assets/images/`
